<a href="https://colab.research.google.com/github/idillpelinn/Pupilica-AI-Python/blob/main/Pupilica_Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***NUMPY***

*  Sayısal veriler üzerinde hızlı çalışmamızı sağlar.
*  Çok boyutlu dizilerle verimli bir şekilde çalışmanıza olanak sağlayan *ndarray* nesnesini sağlar. Bu diziler, Python listelerinden daha hızlıdır ve verimli bir şekilde saklanır.
*  Diziler üzerinde matematiksel işlemler gerçekleştirmek için birçok fonksiyon sağlar. Örneğin, dizilerin toplamını, ortalamasını, standart sapmasını ve daha fazlasını hesaplamak için NumPy'yi kullanabilirsin.
*  Doğrusal cebir işlemleri için fonksiyonlar sağlar. Örneğin, matris çarpımı, tersini alma, özdeğerleri ve özvektörleri hesaplamak için NumPy'yi kullanabilirsin.
*  Verileri işlemek için fonksiyonlar sağlar. Örneğin, verileri sıralamak, filtrelemek, yeniden şekillendirmek ve daha fazlası için NumPy'yi kullanabilirsiniz.

In [1]:
#Numpy kütüphanesini kullanmak için import ile projemize dahil etmemiz gerekiyor
import numpy as np

In [4]:
numpy_array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
numpy_array

numpy.ndarray

In [5]:
# numpy array boyut sayısını öğrenmek için : ndim()
#numpy arraydaki her boyutta bulunan eleman sayılarını döndürür
#toplam eleman sayısı için : size() kullanılır.
print("dimension: ",numpy_array.ndim) #boyut sayısı 1D
print("shape: ",numpy_array.shape) # 15x1 lik vektör
print("size: ",numpy_array.size) #toplam eleman sayısı
print("type:  ", type(numpy_array))

dimension:  1
shape:  (15,)
size:  15
type:   <class 'numpy.ndarray'>


In [8]:
from types import new_class
new_numpy_array = numpy_array.reshape(3,5)
print(new_numpy_array)
print("dimension: ",new_numpy_array.ndim) #boyut sayısı 2 : 2D
print("shape: ",new_numpy_array.shape) # 3x5lik matris
print("size: ",new_numpy_array.size) #toplam eleman sayısı:15
print("type:  ", type(new_numpy_array))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
dimension:  2
shape:  (3, 5)
size:  15
type:   <class 'numpy.ndarray'>



np.zers()--> sıfırlardan oluşan matris,
np.ones() --> birlerden oluşan matris.

  Peki neden kullanırız?
* Başlangıç Değerleri: Bir diziyi belirli bir değerle (sıfır veya bir) başlatmak için.
* Yer Tutucular: Daha sonra doldurulacak bir dizi için yer ayırmak için.
* Maskeleme: Belirli elemanları seçmek veya gizlemek için (sıfırlar genellikle maskeleme için kullanılır).
* Matematiksel İşlemler: Matris işlemlerinde veya diğer hesaplamalarda sıfır veya bir dizileri kullanmak için.

In [9]:
#sıfırlardan oluşan array
nump_array_zeros = np.zeros((3,4))
nump_array_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
#Birlerden oluşan array
nump_array_ones = np.ones((3,4))
nump_array_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
#empty array de oluşturabiliriz. İçerisindeki değerler random olarak belirlenir.
nump_array_empty = np.empty((5,4))
nump_array_empty

array([[0. , 0. , 0.3, 1. ],
       [0. , 0. , 1. , 1. ],
       [1. , 1. , 1. , 1. ],
       [1. , 0. , 0. , 1. ],
       [0.5, 0. , 0. , 1. ]])

In [14]:
#arange(x , y , basamak) : xten başlayarak y'ye kadar (y dahil değil) +basamak kadar ilerler
nump_array_arange = np.arange(10,50,5)
nump_array_arange

array([10, 15, 20, 25, 30, 35, 40, 45])

In [16]:
#linspace(x, y , basamak) : xten başlayarak y'ye(y dahil) kadar basamak sayısına böler aslında basamak tane sayı oluşturmuş olur
nump_array_linspace = np.linspace(10,50,15)
nump_array_linspace

array([10.        , 12.85714286, 15.71428571, 18.57142857, 21.42857143,
       24.28571429, 27.14285714, 30.        , 32.85714286, 35.71428571,
       38.57142857, 41.42857143, 44.28571429, 47.14285714, 50.        ])

# Numpy Temel Operasyonları

In [17]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [18]:
print("Toplama: ", a+b)
print("Cikarma: ", a-b)
print("Dizinin kendisi ile carpimi (karesi) : ", a**2)

Toplama:  [5 7 9]
Cikarma:  [-3 -3 -3]
Dizinin kendisi ile carpimi (karesi) :  [1 4 9]


In [19]:
# filtreleme
a = np.array([1,2,3])
filtre = a < 2 # a array'nin icerisinde bulunan 2 den kucuk degerleri goster
filtre

array([ True, False, False])

In [20]:
#matris çarpımı (1*4) + (2*5) + (3*6)
a.dot(b)

32

In [28]:
a = np.array([[1,2,3],[4,5,6]]) # 2x3
b = np.array([[4,5,6],[1,2,3]]) # 2x3 ->T-> 3x2

"""
T transpoz alma işlemini ifade eder:
matris çarpımı yapmak ilk matrisin sütun sayısı ikinci matrisin satır sayısına eşit olmalıdır.
A matrisi 3 x 4 boyutunda olsun.
B matrisi 4 x 2 boyutunda olsun.
A ve B matrisleri çarpılabilir, çünkü A'nın sütun sayısı (4) B'nin satır sayısına (4) eşittir.
Sonuç matrisi 3 x 2 boyutunda olacaktır.
"""

b.T
a.dot(b.T)


array([[32, 14],
       [77, 32]])

In [31]:
#sum() : her sütunu kendi içinde toplar
a = np.array([[1,2,3],
              [4,5,6]])
print("sum: ", sum(a))

#np.sum() : bütün elemanların toplamı
print("np.sum: ", np.sum(a))

# sütunları np ile toplamak için axis=0 kullanabiliriz
print("np.sum(axis=0): ", np.sum(a, axis=0))

#satırları np ile toplamak için axis=1 kullanabiliriz
print("np.sum(axis=1): ", np.sum(a, axis=1))


sum:  [5 7 9]
np.sum:  21
np.sum(axis=0):  [5 7 9]
np.sum(axis=1):  [ 6 15]


In [39]:
a = np.array([[1,2,3],
              [4,5,6]])
#max()
print("max:", a.max())
# np.max()
print("npmax: ", np.max(a))
print("npmax:(sütun) ", np.max(a, axis=0))
print("npmax:(satır) ", np.max(a, axis=1))

max: 6
npmax:  6
npmax:(sütun)  [4 5 6]
npmax:(satır)  [3 6]


In [40]:
a = np.array([[1,2,3],
              [4,5,6]])
#min()
print("min:", a.min())
# np.min()
print("npmin: ", np.min(a))
print("npmin:(sütun) ", np.min(a, axis=0))
print("npmin:(satır) ", np.min(a, axis=1))

min: 1
npmin:  1
npmin:(sütun)  [1 2 3]
npmin:(satır)  [1 4]


In [41]:
# satir satir toplama
a.sum(axis = 1)

array([ 6, 15])

In [42]:
# sutun sutun toplama
a.sum(axis = 0)

array([5, 7, 9])

In [43]:
# kare koku
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [45]:
# elemanların karesi
print(np.square(a))
print(a**2)

[[ 1  4  9]
 [16 25 36]]
[[ 1  4  9]
 [16 25 36]]


In [47]:
#random.rand() fonksiyonu, 0 ile 1 arasında rastgele sayılar üretmek için kullanılır. Üretilen sayılar, düzgün dağılımlıdır, yani her sayının seçilme olasılığı eşittir.
#boyutlarını alır (2,3)
np.random.rand(3,3)

array([[0.84221518, 0.22675399, 0.10878031],
       [0.8067476 , 0.3183473 , 0.65075578],
       [0.55582833, 0.83857178, 0.16421472]])

In [48]:
#random.random() 0.0 ile 1.0 arasında rastgele kayan noktalı sayılar üretmek için kullanılır. Üretilen sayılar, yarı açık aralıkta yer alır, yani 0.0 dahil edilirken 1.0 hariç tutulur.
#boyutları tuple olarak alır ((2,3))
np.random.random((3,3))


array([[0.97082533, 0.89955846, 0.56744328],
       [0.65570892, 0.57980492, 0.60846729],
       [0.52516961, 0.12087606, 0.28015162]])

In [49]:
#random.normal(): normal dağılıma (Gauss dağılımı) sahip rastgele sayılar üretmek için kullanılır.
rastgele_dizi = np.random.normal(0 ,1 , (5,3)) # normal dagilima 0 ortalamali 1 std, 5 adet deger uret
rastgele_dizi

array([[ 0.1244944 , -0.16841764, -1.01640386],
       [-0.21388584, -1.7992132 ,  0.25395501],
       [ 0.4725666 ,  0.57625737,  1.23707154],
       [-0.63564479, -0.26617006,  0.44686822],
       [ 0.20511871,  0.47124842, -0.62165478]])

**İndexleme ve Slicing**

In [50]:
dizi= np.array([1,2,3,4,5,6,7])
dizi[3]

4

In [56]:
dizi[0:4] # 0--4
dizi[:4] #4e kadar
dizi[::-1]#tersten

array([7, 6, 5, 4, 3, 2, 1])

In [61]:
dizi2D = np.array([[1,2,3,4,5],[6,7,8,9,10]])
dizi2D[1,2]  # 1.indise sahip satır ( 2.satır) ve 2.indise sahip sütun(3.sütun) kesişimi [8]
dizi2D[1,:] #1.indisli satır ve bütün sütunlar [6,7,8,9,10]
dizi2D[:,2] #bütün satırlar , 2.insize sahip sütun[3,8]
dizi2D[ 0, 0:2] #0.indisli satır ve 0dan2ye kadar sütun [1,2]

array([1, 2])

In [62]:
dizi2D[:, 2:4]

array([[3, 4],
       [8, 9]])

In [64]:
dizi2D[-1, :] #sonuncu satur bütün sütunlar

array([ 6,  7,  8,  9, 10])

In [65]:
dizi2D[[0,1], [1,3]]

array([2, 9])

**Shape Manipulation**

In [66]:
numpy_array_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
numpy_array_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
numpy_array_2D_shape= numpy_array_2D.shape
numpy_array_2D_shape

(3, 3)

In [ ]:
#reshape() verilen boyutlarda array oluşturur
""""
[[1,2]
[3,4]]

reshape(4,-1) --> 2x2 lik matrisi 4x1 lik matris yapar

[1,2,3,4]

In [96]:

#numpy_array_2D_shape[0] --> satır sayısı YANİ 3
#numpy_array_2D_shape[1] --> sütun sayısı YANİ 3
#3*3 = 9 oldu
#(9,1)> 9x1 lik bir vektör oluşturdu

numpy_array_2D.reshape(numpy_array_2D_shape[0] * numpy_array_2D_shape[1] , 1)



array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [70]:
numpy_array_2D.reshape(numpy_array_2D_shape[0] * numpy_array_2D_shape[1] , -1)
# -1 olması sütun boyutunun oto olarak atanmasını sağlar.


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [71]:
# ravel() :Aslında yukardaki işlemi yapıyor yani çok boyutlu bir arrayi tek boyutlu arraya dönüştürür
numpy_array_2D.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
# A array = 2 boyutlu bir tane array -> (3,5)
#B array = 1 boyutlu bir tane array -> (15,)
#C = A + B
#D=linspace ve E=arange ile (3,5) lik matrisler olusturalim.
#F = D+E
import numpy as np
A = np.random.rand(3,5)
B = np.arange(15)   # 0'dan 14'e kadar sayıları içeren bir dizi
B=B.reshape(3,5)
C = A + B
D = np.linspace(10,50,15).reshape(3,5)
E = np.arange(10,160,10).reshape(3,5)
F = D + E
#C'nin ve F'nin her bir elemanini for dongusu ile eleman eleman carpip G = (15,1) boyutunda elde edelim.
G=[]
for i in range (C.shape[0]): #satır sayısı : 3
  for j in range(C.shape[1]): #sütun sayısı : 5
    G.append(C[i,j] * F[i,j])
print("G shape: ",np.array(G).shape)

#toplam degerleri eger 1 den buyukse G1 isimli bir listeye atalim, else ise G2 isimli listeye atalim
C = C.reshape(15,1)
F= F.reshape(15,1)
G1=[]
G2=[]
C.shape[0]
for i in range(C.shape[0]):
  toplam=C[i,0]+F[i,0]
  if toplam>1:
    G1.append(toplam)
  else:
    G2.append(toplam)
  G1.append(toplam)
print(G1,G2)

#C ve F'yi (15,1) sonrasında C'nin ilk elemani ile F'nin son elemani toplayarak ilerleyelim.
C_flat = C.reshape(-1, 1)  # -1 otomatik olarak 15 elemanı kullanır
F_flat = F.reshape(-1, 1)

# G1 ve G2 listelerini tanımlama
G1 = []
G2 = []

# C'nin ilk elemanı ve F'nin son elemanı toplama işlemi ile ilerleme
for i in range(len(C_flat)):  # C_flat'in uzunluğunu kullanarak döngüyü oluştur
    toplam = C_flat[i, 0] + F_flat[len(F_flat) - 1 - i, 0]  # len kullanarak sondan eleman al
    if toplam > 1:
        G1.append(toplam)
    else:
        G2.append(toplam)
# Sonuçları yazdırma
print("G1 (Toplam > 1 olanlar):", G1)
print("G2 (Toplam <= 1 olanlar):", G2)

G shape:  (15,)
[20.903685222047415, 20.903685222047415, 34.28148319397098, 34.28148319397098, 47.85637710688183, 47.85637710688183, 62.486692120638565, 62.486692120638565, 75.56272795499503, 75.56272795499503, 89.3455050375616, 89.3455050375616, 103.69856435309477, 103.69856435309477, 117.29449520828896, 117.29449520828896, 131.52654479172946, 131.52654479172946, 144.9145883902157, 144.9145883902157, 158.9644934984972, 158.9644934984972, 173.20149378798533, 173.20149378798533, 186.29439245737078, 186.29439245737078, 201.07418506094214, 201.07418506094214, 214.75512437328516, 214.75512437328516] []
G1 (Toplam > 1 olanlar): [200.90368522204741, 188.56719747968526, 176.4278056783104, 165.34383497778143, 152.70558509785215, 140.77407646613304, 129.41285006738048, 117.29449520828896, 105.81225907744374, 93.48601696164427, 81.82163635564008, 70.34435093084244, 57.72296388594221, 46.788470775227864, 34.755124373285156]
G2 (Toplam <= 1 olanlar): []
